app/urls.py
from django.conf.urls import url

from app import views

urlpatterns = [
    url(r'^$', views.index, name='index'),   # 主页
    url(r'^mycart/$', views.mycart, name='mycart'),   # 购物车
    url(r'^login/$', views.login, name='login'),   # 登录
    url(r'^register/$', views.register, name='register'),   # 注册
    url(r'^detail/$', views.detail, name='detailbase'),  #商品详情
    url(r'^detail/(?P<num>\d+)/$', views.detail, name='detail'),
    url(r'^logout/$', views.logout, name='logout'),  # 注销
    url(r'^checkusername/$', views.checkusername, name='checkusername'),  # 验证帐号
    url(r'^addcart/$', views.addcart, name='addcart'),  # 加入购物车
    url(r'^subcart/$', views.subcart, name='subcart'),  # 删减购物车
    url(r'^changecartselect/$', views.changecartselect, name='changecartselect'),  # 购物车商品选中状态
    url(r'^changecartall/$', views.changecartall, name='changecartall'),  # 全选/取消全选
    url(r'^mkorder/$', views.mkorder, name='mkorder'),    # 生成订单
    url(r'orderlist/$', views.orderlist, name='orderlist'), # 订单列表
    url(r'^orderdetail/(?P<identifier>[\d.]+)/$', views.orderdetail, name='orderdetail'),  # 订单详情
    url(r'^deletecart/$', views.deletecart, name='deletecart'),  # 删除单个物品
    url(r'^newbuy/$', views.newbuy, name='newbuy'),  # 立即购买
    url(r'^returnurl/$', views.returnurl, name='returnurl'),  # 支付成功后，客户端的显示
    url(r'^appnotifyurl/$', views.appnotifyurl, name='appnotifyurl'),  # 支付成功后，订单的处理
    url(r'^pay/$', views.pay, name='pay'),  # 支付
]

seven/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('app.urls', namespace='seven'))
]

app/models.py
from django.db import models

class Wheel(models.Model):
    img = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    trackid = models.CharField(max_length=20)
    class Meta:
        db_table = 'seven_wheel'


class User(models.Model):
    username = models.CharField(max_length=40)
    password = models.CharField(max_length=256)
    phone = models.CharField(max_length=20)
    class Meta:
        db_table = 'seven_user'


class Detail(models.Model):
    productid = models.CharField(max_length=10)  # 图片ID
    img = models.CharField(max_length=256)  # 图片
    name = models.CharField(max_length=100)  # 图片名
    specifics = models.CharField(max_length=100)  # 详情
    price = models.FloatField()  # 价格
    marketprice = models.FloatField()  # 原价
    class Meta:
        db_table = 'seven_detail'


class Goods(models.Model):
    productid = models.CharField(max_length=10)  # 图片ID
    img = models.CharField(max_length=256)  # 图片
    name = models.CharField(max_length=100)  # 图片名
    specifics = models.CharField(max_length=100)  # 详情
    price = models.FloatField()  # 价格
    marketprice = models.FloatField()  # 原价
    class Meta:
        db_table = 'seven_goods'


class Cart(models.Model):
    # 用户[添加的这个商品属于哪个用户]
    user = models.ForeignKey(User)
    # 商品[添加的是哪个商品]
    goods = models.ForeignKey(Goods)
    # 商品数量
    number = models.IntegerField()
    # 是否选中
    isselect = models.BooleanField(default=True)
    # 是否删除
    isdelete = models.BooleanField(default=False)
    class Meta:
        db_table = 'seven_cart'


class Order(models.Model):
    # 用户
    user = models.ForeignKey(User)
    # 创建时间
    createtime = models.DateTimeField(auto_now_add=True)
    # 更新时间
    updatetime = models.DateTimeField(auto_now=True)
    # 状态
    status = models.IntegerField(default=0)
    # 订单号
    identifier = models.CharField(max_length=256)


# 订单商品 模型类
# 一个订单 对应 多个商品(订单商品)
class OrderGoods(models.Model):
    # 订单
    order = models.ForeignKey(Order)
    # 商品
    goods = models.ForeignKey(Goods)

    ## 商品选择规格
    number = models.IntegerField()

templates/order/orderdetail.html
{% load static %}

<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>坑爹订单详情</title>
        <link rel="stylesheet" type="text/css" href="{% static 'index/css/reset.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'index/css/index.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'register/css/register.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'mycart/css/mycat.css' %}">
	</head>
    <body>
    <div id="register">
			<div class="center">
				<ul id="list1">
					<li><a href="../index/index.html">七加二商城</a></li>
					<li class="kuan"><a href="#"> 装备酷</a></li>
					<li class="kuan"><a href="#"> 相伴</a></li>
					<li class="kuan"><a href="#">移动端</a></li>
				</ul>
				<ul id="list2">
					<li>您好,欢迎来到七加二商城！</li>
					<li>
                        {% if user %}
                            <a>{{ user.username }}</a>
                        {% else %}
                            <a href="{% url 'seven:login' %}">登录</a>
                        {% endif %}
                    </li>
					<li>
                        {% if user %}
                            <a href="{% url 'seven:logout' %}">注销</a>
                        {% else %}
                            <a href="{% url 'seven:register' %}">注册</a>
                        {% endif %}
                    </li>
					<li class="qq"><a href="#"></a></li>
					<li class="weibo"><a href="#"></a></li>
					<li class="kuan"><a href="{% url 'seven:orderlist' %}">我的订单</a></li>
					<li class="kuan"><a href="#">站内消息</a></li>
					<li class="kuan"><a href="#">帮助中心</a></li>
				</ul>

			</div>
		</div>
		<!---->
    <div id="logo">
			<div class="center">
				<div class="logo_left">
					<a href="{% url 'seven:index' %}"><img src="{% static 'mycart/img/201511170959056304.png' %}"></a>
				</div>
				<div class="logo_center" id="lct">
					<div class="triangle"></div>
					<img src="{% static 'index/img/logo/search.png' %}">
					<form>
						<input type="text" class="ipt1">
						<input type="submit" value="搜索" class="ipt2">

					</form>

				</div>

			</div>
		</div>
    <div class="orderdetail">
        <p>
            订单号: {{ order.identifier }}
        </p>
        <ul>
            {% for ordergoods in order.ordergoods_set.all %}
            <li>
                <span>{{ ordergoods.goods.specifics }}</span>
                &nbsp;<span>单价：{{ ordergoods.goods.price }}</span>
                <i>数量x{{ ordergoods.number }}</i>
            </li>
            {% endfor %}
        </ul>
        <p></p>
        {% if order.status == 0 %}
            <button class="btn btn-default" id="alipay" data-orderid="{{ order.id }}">支付</button>
        {% endif %}

        <br>
        您还可以继续<a href="{% url 'seven:index' %}">选购</a>
    </div>
    <div id="foot">
                <div class="center">
                    <div id="footer">
                        <p>©2005-2015 七加二驴友商城 版权所有，并保留所有权利。天津市华苑产业园区鑫茂民营科技园C2座6层AB单元</p>
                        <p>Tel: 022-23857290-8031 QQ: 191391765</p>
                        <p>ICP备案证书号:津ICP备14004534号-1</p>
                    </div>
                </div>
            </div>
    <div id="fxdc">
			<div class="fxdc_left">
				<ul>
				<li><a href="../index/index.html"><img src="{% static 'register/img/wechat-pic.png' %}">
				<dl>
					<dt>七加二商城</dt>
					<dt>APP下载</dt>
					<dd>注册送5元</dd>
				</dl></a></li>
				<li><a href="../index/index.html"><img src="{% static 'register/img/wechat-pic.png' %}">
				<dl>
					<dt>七加二</dt>
					<dt>官方微信</dt>
					<dd>lvtuan_net</dd>
				</dl></a></li>
			</ul>
			</div>
			<div class="fxdc_right">
				<img src="{% static 'register/img/icon_24.png' %}">
			</div>
		</div>

</body>
</html>
<script src="{% static 'index/js/jquery.js' %}"></script>
<script src="{% static 'mycart/js/orderdetail.js' %}"></script>

templates/order/orderlist.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
		<meta charset="UTF-8">
		<title></title>

		<link rel="stylesheet" type="text/css" href="{% static 'index/css/reset.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'index/css/index.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'register/css/register.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'mycart/css/mycat.css' %}">

	</head>
	<body>
		<div id="register">
			<div class="center">
				<ul id="list1">
					<li><a href="../index/index.html">七加二商城</a></li>
					<li class="kuan"><a href="#"> 装备酷</a></li>
					<li class="kuan"><a href="#"> 相伴</a></li>
					<li class="kuan"><a href="#">移动端</a></li>
				</ul>
				<ul id="list2">
					<li>您好,欢迎来到七加二商城！</li>
					<li>
                        {% if user %}
                            <a>{{ user.username }}</a>
                        {% else %}
                            <a href="{% url 'seven:login' %}">登录</a>
                        {% endif %}
                    </li>
					<li>
                        {% if user %}
                            <a href="{% url 'seven:logout' %}">注销</a>
                        {% else %}
                            <a href="{% url 'seven:register' %}">注册</a>
                        {% endif %}
                    </li>
					<li class="qq"><a href="#"></a></li>
					<li class="weibo"><a href="#"></a></li>
					<li class="kuan"><a href="{% url 'seven:orderlist' %}">我的订单</a></li>
					<li class="kuan"><a href="#">站内消息</a></li>
					<li class="kuan"><a href="#">帮助中心</a></li>
				</ul>
				
			</div>
		</div>
		<!---->
		<div id="logo">
			<div class="center">
				<div class="logo_left">
					<a href="{% url 'seven:index' %}"><img src="{% static 'mycart/img/201511170959056304.png' %}"></a>
				</div>
				<div class="logo_center" id="lct">
					<div class="triangle"></div>
					<img src="{% static 'index/img/logo/search.png' %}">
					<form>
						<input type="text" class="ipt1">
						<input type="submit" value="搜索" class="ipt2">
						
					</form>
					
				</div>
				
			</div>
		</div>
    <div class="orderlist">
        {% for order in orders %}
            <p class="bg-info" style="float: left;margin-left: 50px">
                <a href="{% url 'seven:orderdetail' order.identifier %}">
                    订单号: {{ order.identifier }} --
                    {% if order.status == 0 %}
                        未付款
                    {% elif order.status == 1 %}
                        待发货
                    {% elif order.status == 2 %}
                        待收货
                    {% elif order.status == 3 %}
                        待评价
                    {% elif order.status == 4 %}
                        已评价
                    {% endif %}
                </a>
            </p>
        {% endfor %}
        
    </div>

</body>
</html>